CREATE TABLE `video` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '视频ID，自增主键',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '上传用户ID，关联user.id',
    `title` VARCHAR(256) NOT NULL COMMENT '视频标题',
    `description` TEXT COMMENT '视频描述',
    `cover_url` VARCHAR(512) NOT NULL COMMENT '封面图URL，对象存储地址',
    `video_url` VARCHAR(512) NOT NULL COMMENT '视频文件URL，对象存储地址',
    `duration` INT UNSIGNED NOT NULL COMMENT '视频时长，单位：秒',
    `size` BIGINT UNSIGNED NOT NULL COMMENT '文件大小，单位：字节',
    `format` VARCHAR(16) NOT NULL COMMENT '视频格式，如mp4、flv',
    `width` SMALLINT UNSIGNED DEFAULT 0 COMMENT '视频宽度（像素）',
    `height` SMALLINT UNSIGNED DEFAULT 0 COMMENT '视频高度（像素）',
    `view_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '播放量',
    `danmaku_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '弹幕数量',
    `like_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点赞数',
    `favorite_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '收藏数',
    `coin_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '投币数（B站特有互动，可选）',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-审核中，1-已发布，2-已删除，3-仅自己可见',
    `category_id` INT UNSIGNED DEFAULT 0 COMMENT '分类ID，关联分类表',
    `tags` VARCHAR(512) DEFAULT '' COMMENT '标签，逗号分隔，如"游戏,原神,攻略"',
    `published_at` DATETIME DEFAULT NULL COMMENT '发布时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（上传时间）',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status_published` (`status`, `published_at`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_view_count` (`view_count`),
    KEY `idx_created_at` (`created_at`),
    KEY `idx_danmaku_count` (`danmaku_count`),
    CONSTRAINT `fk_video_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视频表';